# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoplusplus < Formula
  desc "A TUI to track your competitive programming grind."
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_darwin_amd64.tar.gz"
      sha256 "423a2a11cd0c02479a9ddd43d8e6f32e42939eda516e4611a47b97a0c8930122"

      def install
        bin.install "todoplusplus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_darwin_arm64.tar.gz"
      sha256 "11a5057e8f44abd83a768d559dbd70a8e21eb0b699b24f18cbfc1d7765c6f149"

      def install
        bin.install "todoplusplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_linux_amd64.tar.gz"
      sha256 "2c1282f9974a484b6b9b124e1f9b5a6b1281fc2e65062886b980db08b62cdcc6"
      def install
        bin.install "todoplusplus"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_linux_arm64.tar.gz"
      sha256 "a3bf1da20cee5616e5d1dbce5695e87a78e0c05744bb2628970bc23e46378b74"
      def install
        bin.install "todoplusplus"
      end
    end
  end

  test do
    system "#{bin}/todoplusplus --help"
  end
end
