# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todoplusplus < Formula
  desc "A TUI to track your competitive programming grind."
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_darwin_amd64.tar.gz"
      sha256 "c1b60d2af8215ac70e391e9b0e0ea7596fc34e6a1c20c38baf64583cad730d89"

      def install
        bin.install "todoplusplus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_darwin_arm64.tar.gz"
      sha256 "d6d6798853b131d635cd27e9913bfb2cfbafa793898d524479ac695cc1bf7622"

      def install
        bin.install "todoplusplus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_linux_amd64.tar.gz"
      sha256 "6340aee95acfc0c36730dad07aa8fd07c986f145336ea882df03511a3dcf85a9"
      def install
        bin.install "todoplusplus"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Harschmann/todoplusplus/releases/download/v0.1.0/todoplusplus_0.1.0_linux_arm64.tar.gz"
      sha256 "3c1cfe1c38fd39fa09682250ba7c128c2b191a6c02c655f993f7093d57920dfb"
      def install
        bin.install "todoplusplus"
      end
    end
  end

  test do
    system "#{bin}/todoplusplus --help"
  end
end
